name: Xlog

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          check-latest: true

      - name: Install xlog
        run: |
          go install github.com/emad-elsaid/xlog/cmd/xlog@latest

      - name: Build
        run: |
          xlog \
          --build . \
          --sitename "cervoliu"
          rm *.md
          chmod -R 0777 .

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v2
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
      #url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3